[build]
  cmds = ["composer install --no-dev", "npm install", "npm run build"]

[variables]
  PHP_EXTENSION_INSTALL = "gd, bcmath, pdo_mysql"

[start]
  cmd = "php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT"
